Fix el7 detection
sclorg/s2i-python-container pull request #438
Opened 2021-04-28 10:33 UTC by frenzymadness

Fixes #437

2021-04-28 10:34 UTC, frenzymadness commented
[test][test-openshift]

2021-04-28 10:57 UTC, pkubatrh commented
LGTM

2021-04-29 12:34 UTC, phracek commented
[test]

2021-04-29 13:53 UTC, phracek commented
CentOS7 failed because of #412 

```bash
15:29:39 [1m[INFO] Running test test_scl_variables_in_dockerfile ... [0m
15:29:39 
15:29:39 
15:29:39 [1m[INFO] Testing variable presence during `docker exec`[0m
15:29:39 
15:29:41  Value /opt/rh/rh-nodejs14/root/usr/share/man is missing from variable MANPATH
15:29:41 MANPATH=/opt/rh/rh-python27/root/usr/share/man:/opt/rh/python27/root/usr/share/man:/opt/rh/httpd24/root/usr/share/man:/opt/rh/rh-nodejs10/root/usr/share/man
15:29:41 
```

2021-04-30 12:44 UTC, phracek commented
[test][test-openshift]

2021-05-03 13:22 UTC, phracek approved these changes
LGTM.

2021-05-03 13:52 UTC, frenzymadness commented
[test][test-openshift]

2021-05-03 14:39 UTC, phracek commented
RHEL7 test failed with reason https://gist.github.com/rhscl-automation/f25fb03415b8bc596d63dfce8962f474#file-s2i-python-container-113-sh-L15010

```bash

[1m[INFO] Test from Dockerfile[0m
test/run: line 223: podman: command not found
Using this Dockerfile:
FROM rhscl/python-38-rhel7:1
```

2021-05-03 14:41 UTC, phracek requested changes

2021-05-03 14:41 UTC, phracek commented on 2.7/test/run
> +  if [[ ${VERSION} == "2.7" ]] || podman inspect ${IMAGE_NAME} --format "{{.Config.Env}}" | tr " " "\n" | grep -q "^PLATFORM=el7"; then
I would prefer to use `docker` and not `podman`

2021-05-03 14:41 UTC, phracek commented on 3.6/test/run
> +  if [[ ${VERSION} == "2.7" ]] || podman inspect ${IMAGE_NAME} --format "{{.Config.Env}}" | tr " " "\n" | grep -q "^PLATFORM=el7"; then
The same here.

2021-05-03 14:41 UTC, phracek commented on 3.8/test/run
> +  if [[ ${VERSION} == "2.7" ]] || podman inspect ${IMAGE_NAME} --format "{{.Config.Env}}" | tr " " "\n" | grep -q "^PLATFORM=el7"; then
The same here

2021-05-03 14:41 UTC, phracek commented on 3.9/test/run
> +  if [[ ${VERSION} == "2.7" ]] || podman inspect ${IMAGE_NAME} --format "{{.Config.Env}}" | tr " " "\n" | grep -q "^PLATFORM=el7"; then
The same here

2021-05-03 14:41 UTC, phracek commented on test/run
> +  if [[ ${VERSION} == "2.7" ]] || podman inspect ${IMAGE_NAME} --format "{{.Config.Env}}" | tr " " "\n" | grep -q "^PLATFORM=el7"; then
Replace `podman` with `docker` and generate new files and tests should passed ;)

2021-05-04 05:03 UTC, frenzymadness commented
Thanks @phracek !

[test][test-openshift]

2021-05-04 07:17 UTC, phracek commented
OpenShift tests failed, because of OpenShift does not start up.

Let's try again.

[test-openshift]

2021-05-04 07:45 UTC, phracek approved these changes
LGTM

2021-05-04 07:45 UTC, merged