Prepare CI for Python 3.12 minimal container image
sclorg/s2i-python-container pull request #705
Opened 2024-08-14 20:46 UTC by frenzymadness

When we merge this, I'll rebase #704

2024-08-20 05:55 UTC, frenzymadness commented
@phracek ping

2024-09-02 07:34 UTC, phracek commented
[test]

2024-09-02 07:35 UTC, phracek commented on .github/workflows/container-tests.yml
> +        version: [ "3.8", "3.9", "3.9-minimal", "3.11", "3.11-minimal", "3.12", "3.12-minimal" ]
In order to test it, this change has to be done as a separate commit.

2024-09-02 07:35 UTC, phracek requested changes
Please address my comment.

2024-09-02 09:36 UTC, phracek approved these changes
Sorry, I was on vacation. LGTM.

2024-09-02 09:41 UTC, merged